export type ADD_NODE = 'ADD_NODE';
export type ADD_NEIGHBOUR_TO_NODE = 'ADD_NEIGHBOUR_TO_NODE';
export type DELETE_NEIGHBOOUR_FROM_NODE = 'DELETE_NEIGHBOUR_FROM_NODE';
export type DELETE_NODE = 'DELETE_NODE';
export type ADD_SIMPLE_EDGE = 'ADD_EDGE';
export type ADD_WEIGHTED_EDGE = 'ADD_WEIGHTED_EDGE';
