export const WALL_NODE_BUTTON = 'WALL_NODE_BUTTON';
export const RESTORE_NODE_BUTTON = 'RESTORE_NODE_BUTTON';
export const WEIGHTED_NODE_BUTTON = 'WEIGHTED_NODE_BUTTON';
export const SOURCE_NODE_BUTTON = 'SOURCE_NODE_BUTTON';
export const DESTINATION_NODE_BUTTON = 'DESTINATION_NODE_BUTTON';

export type NodeTypeButtonType =
    | typeof WALL_NODE_BUTTON
    | typeof RESTORE_NODE_BUTTON
    | typeof WEIGHTED_NODE_BUTTON
    | typeof SOURCE_NODE_BUTTON
    | typeof DESTINATION_NODE_BUTTON;
